version: '3'

services:
  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: amd64/mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
